spring.application.name=API-GATEWAY
server.port=8083

#routes configuration
spring.cloud.gateway.routes[0].id=QUIZ-SERVICE
spring.cloud.gateway.routes[0].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path= /quiz/**
spring.cloud.gateway.routes[0].filters=AuthenticationFilter


spring.cloud.gateway.routes[1].id=QUESTION-SERVICE
spring.cloud.gateway.routes[1].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path= /question/**
spring.cloud.gateway.routes[1].filters=AuthenticationFilter


spring.cloud.gateway.routes[2].id=AUTH-SERVICE
spring.cloud.gateway.routes[2].uri=lb://AUTH-SERVICE
#spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/register
#spring.cloud.gateway.routes[2].predicates[1]=Path=/auth/token
#spring.cloud.gateway.routes[2].predicates[2]=Path=/auth/validate
spring.cloud.gateway.routes[2].predicates[0]=Path= /auth/**
